var t = 'NODE'
var letter = `${t}\n\nTEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD ${t} TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD`

console.log(letter)
