var t = 'NODE'
var letter = t + 'TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD' + t + 'TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD TEST HELLO WORLD'
console.log(letter);
